version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "LATEST"
      TYPE: "EDU"
    volumes:
      - minecraft_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  minecraft_data: