

services:
  minetest:
    image: lscr.io/linuxserver/minetest:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      CLI_ARGS: "--gameid minetest_game"
    volumes:
      - minetest_data_volume:/config/.minetest
    ports:
      - target: 30000
        published: 30000
        protocol: udp
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 500M
          cpus: "0.5"
        reservations:
          memory: 256M

  minetest-worker:
    image: lscr.io/linuxserver/minetest:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      CLI_ARGS: "--gameid minetest_game"
    volumes:
      - minetest_worker_data:/config/.minetest
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 500M
          cpus: "0.5"
        reservations:
          memory: 256M

volumes:
  minetest_data_volume:
  minetest_worker_data:
