version: '3.8'

services:
  minetest-server:
    image: minetest/minetest:5.6.0  
    deploy:
      replicas: 3  
      resources:
        limits:
          cpus: '1.0'  
          memory: 1G  
        reservations:
          cpus: '0.5'  
          memory: 512M  
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure 
      labels:
        - "minetest=true"  
    ports:
      - "30001:30000"  
    volumes:
      - minetest-world:/minetest/worlds  # Volume pour persister les mondes
      - minetest-backups:/minetest/backups  # Volume pour les sauvegardes
    environment:
      - MINETEST_HOME=/minetest
      - MINETEST_BACKUP_INTERVAL=1440  # Effectuer une sauvegarde tous les jours (en minutes)
    networks:
      - minetest-net

volumes:
  minetest-world:
    driver: local  
  minetest-backups:
    driver: local 

networks:
  minetest-net:
    driver: overlay  # Réseau Overlay pour Swarm, permet une communication entre nœuds du Swarm
