version: '3.8'

services:
  minetest-server:
    build:
      context: .               
      dockerfile: Dockerfile   
    image: minetest-server-image:latest  # Le nom de l'image une fois construite
    deploy:
      replicas: 3  # Nombre d'instances du serveur Minetest
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
      placement:
        constraints: [node.role == worker]  # Exécuter sur des nœuds de travail
    ports:
      - "30001:30000"  # Exposer le port 30001 pour les connexions (modifié pour éviter les conflits)
    volumes:
      - minetest-world:/minetest/worlds  # Volume pour persister les mondes
    environment:
      - MINETEST_HOME=/minetest
    networks:
      - minetest-net

volumes:
  minetest-world:
    driver: local

networks:
  minetest-net:
    driver: overlay
