services:
  minetest:
    image: lscr.io/linuxserver/minetest:latest
    container_name: minetest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - "CLI_ARGS=--gameid minetest_game" 
    volumes:
      - /path/to/minetest/data:/config/.minetest
    ports:
      - 30000:30000/udp
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure