
services:
  minetest-worker:
    image: lscr.io/linuxserver/minetest:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      CLI_ARGS: "--gameid minetest_game"
    volumes:
      - minetest_worker_data:/config
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

volumes:
  minetest_worker_data:
