version: "3.9"

services:
  minetest:
    image: lscr.io/linuxserver/minetest:latest
    container_name: minetest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      CLI_ARGS: "--gameid minetest_game"
    volumes:
      - /mnt/data/minetest_data:/config/.minetest
    ports:
      - target: 30000
        published: 30000
        protocol: udp
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 500M
          cpus: "0.5"
        reservations:
          memory: 256M

  minetest-worker:
    image: lscr.io/linuxserver/minetest:latest
    container_name: minetest-worker
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      CLI_ARGS: "--gameid minetest_game"
    volumes:
      - /mnt/data/minetest_worker:/config/.minetest
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 500M
          cpus: "0.5"
        reservations:
          memory: 256M
