FROM minetest/minetest:5.6.0

# Ajouter un script de sauvegarde personnalisé
COPY backup.sh /usr/local/bin/backup.sh
RUN chmod +x /usr/local/bin/backup.sh

# Créer un cron job pour effectuer la sauvegarde tous les jours à 00h00
RUN echo "0 0 * * * /usr/local/bin/backup.sh" > /etc/cron.d/minetest-backup

# Exposer le port pour Minetest
EXPOSE 30000
