# Dockerfile simplifié pour le serveur Minetest
FROM alpine:3.12

RUN apk update && \
    apk add --no-cache cmake g++ make libjpeg-turbo-dev zlib-dev && \
    wget https://github.com/minetest/minetest/archive/refs/tags/5.4.1.tar.gz && \
    tar -xzvf 5.4.1.tar.gz && \
    cd minetest-5.4.1 && \
    cmake . && \
    make -j$(nproc) && \
    make install

EXPOSE 30000/udp

ENTRYPOINT ["minetest", "--server", "--world", "/root/.minetest/worlds/world"]
