services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "24555:24555"
    environment:
      EULA: "TRUE"
      VERSION: "LATEST"
      TYPE: "VANILLA"
      MODE: "creative"
      DIFFICULTY: "peaceful"
      HARDCORE: "false"
      PVP: "false"
      MAX_PLAYERS: "10"
      MOTD: "Bienvenue sur le serveur Minecraft de l'ETML"
      # LEVEL: Poudlard
    volumes:
      - minecraft_data:/data
      # - ./map/Poudlard:/data/world
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker  # Exécute uniquement sur les nœuds workers
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - minecraft_network

volumes:
  minecraft_data:

networks:
  minecraft_network:
    driver: overlay
