
services:
  minetest:
    image: lscr.io/linuxserver/minetest:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      CLI_ARGS: "--gameid minetest_game"
    volumes:
      - minetest_data_volume:/config
    ports:
      - target: 30000
        published: 30000
        protocol: udp
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

volumes:
  minetest_data_volume:
