version: '3.9'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "LATEST"
      TYPE: "VANILLA"
    volumes:
      - minecraft_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

volumes:
  minecraft_data:

  minetest_worker_data:
